spring.application.name=ArtistAnalyzerProsumerREST

musicstats.uri=http://${MUSIC_STATS_HOST}:${MUSIC_STATS_PORT}
streamingavailability.uri=http://${STREAMING_AVAILABILITY_HOST}:${STREAMING_AVAILABILITY_PORT}

server.port=${SERVER_PORT}
