spring.application.name=ArtistAnalyzerProsumerREST


# Enable if NOT are using Eureka for service discovery
#musicstats.uri=http://${MUSIC_STATS_HOST:localhost}:${MUSIC_STATS_PORT:9001}
#streamingavailability.uri=http://${STREAMING_AVAILABILITY_HOST:localhost}:${STREAMING_AVAILABILITY_PORT:9003}

# Enable for Eureka service discovery
musicstats.uri=http://MusicStatsProviderProsumerREST
streamingavailability.uri=http://StreamingAvailabilityProviderREST

server.port=${SERVER_PORT:9002}

# URL server Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# springdoc.swagger-ui use this namespace for swagger properties