services:
  ticketing-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./DB/infos.sql:/docker-entrypoint-initdb.d/1_infos.sql
      - ./DB/streaming.sql:/docker-entrypoint-initdb.d/2_streaming.sql
      - ./DB/tickets.sql:/docker-entrypoint-initdb.d/3_tickets.sql
      - ./DB/reseller.sql:/docker-entrypoint-initdb.d/4_reseller.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  ticketing-phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    links:
      - "ticketing-mysql:db"
    depends_on:
      - ticketing-mysql

  gateway:
    build: ./Gateway
    ports:
      - "9000:9000"
    environment:
      MUSIC_STATS_HOST: music-stats-microservice
      MUSIC_STATS_PORT: 9050
      ARTIST_ANALYZER_HOST: artist-analyzer-microservice
      ARTIST_ANALYZER_PORT: 9071
      SERVER_PORT: 9000
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-service:8761/eureka/

  discovery-service:
    build: ./DiscoveryService
    ports:
      - "8761:8761"
    environment:
      EUREKA_HOST: discovery-service
      SERVER_PORT: 8761


  legacy-box-office-microservice:
    build: ./LegacyBoxOfficeProviderSOAP
    ports:
      - "9045:8080"
    environment:
      MYSQL_HOST: ticketing-mysql
      MYSQL_PORT: 3306
      MYSQL_DB: ticketing
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      ticketing-mysql:
        condition: service_healthy
    deploy:
      replicas: 1

  #  music-stats-microservice:
  #    build: ./MusicStatsProviderProsumerREST
  #    ports:
  #      - "9050:9050"
  #    environment:
  #      SERVER_PORT: 9050
  #      CONFIG_SERVER_HOST: config-server
  #      CONFIG_SERVER_PORT: 8888
  #      EUREKA_SERVER: http://discovery-service:8761/eureka/
  #      MYSQL_HOST: ticketing-mysql:3306
  #      MYSQL_DB: MusicStats
  #      MYSQL_USER: root
  #      MYSQL_PASSWORD: root
  #    depends_on:
  #      ticketing-mysql:
  #        condition: service_healthy
  #    deploy:
  #      replicas: 1



  ticket-reseller-microservice:
    build: ./TicketResellerProviderREST
    ports:
      - "9061:8080"
    environment:
      SERVER_PORT: 9061
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-service:8761/eureka/
      EUREKA_HOSTNAME: ticket-reseller-microservice
      MYSQL_HOST: ticketing-mysql
      MYSQL_DB: reseller
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - ticketing-mysql
    deploy:
      replicas: 1

#  ticket-searcher-microservice:
#    build: ./TicketSearcherProsumerREST
#    ports:
#      - "9066-9070:9066"
#    environment:
#      SERVER_PORT: 9066
#      CONFIG_SERVER_HOST: config-server
#      CONFIG_SERVER_PORT: 8888
#      EUREKA_SERVER: http://discovery-server:8761/eureka/
#      LEGACY_BOX_OFFICE_URL: http://legacy-box-office-microservice:8080
#      RESELLER_URL: http://ticket-reseller-microservice:8080
#    depends_on:
#      - discovery-service
#      - legacy-box-office-microservice
#      - ticket-reseller-microservice
#    deploy:
#      replicas: 1

#  artist-analyzer-microservice:
#    build: ./ArtistAnalyzerProsumerREST
#    ports:
#      - "9071:9071"
#    environment:
#      MUSIC_STATS_HOST: music-stats-microservice
#      MUSIC_STATS_PORT: 9050
#      STREAMING_AVAILABILITY_HOST: streaming-availability-microservice
#      STREAMING_AVAILABILITY_PORT: 9056
#      SERVER_PORT: 9071
#      CONFIG_SERVER_HOST: config-server
#      CONFIG_SERVER_PORT: 8888
#      EUREKA_SERVER: http://discovery-service:8761/eureka/
##      MYSQL_HOST: ticketing-mysql:3306
##      MYSQL_DB: ticketing
##      MYSQL_USER: root
##      MYSQL_PASSWORD: root
#    depends_on:
#      ticketing-mysql:
#        condition: service_healthy
#    deploy:
#      replicas: 1
volumes:
  mysql-data: