spring.application.name=StreamingAvailabilityProsumerREST

spring.profiles.active=dev

#spring.config.import=optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}
#
#spring.cloud.config.fail-fast=true

# 2. CONFIGURAZIONE DIRETTA DEL DATABASE (Esempio con MySQL)
# Se il database gira sul tuo computer fuori da docker, usa 'localhost'
spring.datasource.url=jdbc:mysql://localhost:3306/StreamingAvaibility?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. CONFIGURAZIONE JPA / HIBERNATE
# update: crea le tabelle automaticamente se non esistono (visto che usi @Entity come in Job.java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. CONFIGURAZIONE URL DI USER-MICROSERVICE (Importante!)
# Nel file UserMicroserviceInvoker.java usi @Value("${microservice.user.find.uri}")
# Ora che non c'è il config server, devi definire questa proprietà qui:
microservice.user.find.uri=http://localhost:9090/
server.port=9090