spring.application.name=TicketSearcherProsumerREST

server.port=${SERVER_PORT:9066}

legacyboxoffice.url=http://legacy-box-office-microservice:8080/LegacyBoxOfficeProviderSOAP/boxoffice
ticketreseller.url=${RESELLER_URL:http://localhost:9061}

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER:http://discovery-service:8761/eureka/}
eureka.instance.prefer-ip-address=false

resttemplate.timeout.connect=3000
resttemplate.timeout.read=5000