# Port of the gateway
server:
  port: ${SERVER_PORT:9000}
  
# Gateway configuration
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: music_stats_route
              uri: http://${MUSIC_STATS_HOST:localhost}:${MUSIC_STATS_PORT:9001}
              predicates:
                - Path=/api/stats/**
              filters:
                - RewritePath=/api/stats/(?<segment>.*), /$\{segment}
                - logPath
            - id: artist_analyzer_route
              uri: http://${ARTIST_ANALYZER_HOST:localhost}:${ARTIST_ANALYZER_PORT:9002}
              predicates:
                - Path=/api/analyze/**
              filters:
                - RewritePath=/api/analyze/(?<segment>.*), /artist-analyzer/$\{segment}
                - logPath


# Eureka client configuration+
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30

# Spring Boot Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Application info
info:
  application:
    name: Api Gateway
    description: GigSync Api Gateway
    version: 1.0.0