# Port of the gateway
server:
  port: ${SERVER_PORT:9010}
  
# Gateway configuration
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: music_stats_route
              uri: http://${MUSIC_STATS_HOST:localhost}:${MUSIC_STATS_PORT:9001}
              predicates:
                - Path=/api/stats/**
              filters:
                - RewritePath=/api/stats/(?<segment>.*), /$\{segment}
                - logPath
            - id: artist_analyzer_route
              uri: http://${ARTIST_ANALYZER_HOST:localhost}:${ARTIST_ANALYZER_PORT:9002}
              predicates:
                - Path=/api/analyze/**
              filters:
                - RewritePath=/api/analyze/(?<segment>.*), /artist-analyzer/$\{segment}
                - logPath

# Spring Boot Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Application info
info:
  application:
    name: Api Gateway
    description: GigSync Api Gateway
    version: 1.0.0